<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="prikab" name="WORKFLOW TESTCASES" tests="30" failures="30" timestamp="17 Aug 2016 23:38:05 GMT" time="735.865" errors="0">
  <testcase name="click_print_view_print" time="17.041" classname="settings.Workflow_TestCases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.Workflow_TestCases.click_print_view_print(Workflow_TestCases.java:25)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- click_print_view_print -->
  <testcase name="relaod_workflow_page" time="18.674" classname="settings.Workflow_TestCases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.Workflow_TestCases.relaod_workflow_page(Workflow_TestCases.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- relaod_workflow_page -->
  <testcase name="update_workflow_name" time="16.001" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_name(WorkflowEdit_testcases.java:15)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_name -->
  <testcase name="empty" time="16.01" classname="settings.WorkflowRestore_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowRestore_testcases.empty(WorkflowRestore_testcases.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- empty -->
  <testcase name="validate_that_workflow_name_is_updated" time="16.255" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_workflow_name_is_updated(WorkflowEdit_testcases.java:28)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_workflow_name_is_updated -->
  <testcase name="update_workflow_name_to_previous" time="16.152" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_name_to_previous(WorkflowEdit_testcases.java:39)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_name_to_previous -->
  <testcase name="validate_that_workflow_name_is_updated_to_previous" time="16.587" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_workflow_name_is_updated_to_previous(WorkflowEdit_testcases.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_workflow_name_is_updated_to_previous -->
  <testcase name="update_workflow_color_" time="12.612" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_color_(WorkflowEdit_testcases.java:63)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_color_ -->
  <testcase name="update_workflow_color_to_previous" time="17.065" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_color_to_previous(WorkflowEdit_testcases.java:76)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_color_to_previous -->
  <testcase name="update_workflow_description" time="16.326" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_description(WorkflowEdit_testcases.java:89)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_description -->
  <testcase name="validate_that_workflow_description_is_updated" time="16.072" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_workflow_description_is_updated(WorkflowEdit_testcases.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_workflow_description_is_updated -->
  <testcase name="update_workflow_description_to_previous" time="16.268" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_description_to_previous(WorkflowEdit_testcases.java:113)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_description_to_previous -->
  <testcase name="validate_that_workflow_description_is_updated_to_previous" time="16.945" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_workflow_description_is_updated_to_previous(WorkflowEdit_testcases.java:129)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_workflow_description_is_updated_to_previous -->
  <testcase name="add_roles" time="16.041" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.add_roles(WorkflowEdit_testcases.java:144)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- add_roles -->
  <testcase name="validate_that_the_roles_in_workflow_are_added" time="16.043" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_the_roles_in_workflow_are_added(WorkflowEdit_testcases.java:158)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_the_roles_in_workflow_are_added -->
  <testcase name="delete_entry_in_role_field" time="16.203" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.delete_entry_in_role_field(WorkflowEdit_testcases.java:169)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- delete_entry_in_role_field -->
  <testcase name="validate_that_the_roles_in_workflow_are_updated" time="16.346" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_the_roles_in_workflow_are_updated(WorkflowEdit_testcases.java:183)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_the_roles_in_workflow_are_updated -->
  <testcase name="update_workflow_role_to_previous" time="16.605" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_role_to_previous(WorkflowEdit_testcases.java:194)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_role_to_previous -->
  <testcase name="validate_that_the_roles_in_workflow_are_updated_to_previous" time="17.572" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_the_roles_in_workflow_are_updated_to_previous(WorkflowEdit_testcases.java:207)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_the_roles_in_workflow_are_updated_to_previous -->
  <testcase name="update_workflow_publish_status" time="18.047" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_publish_status(WorkflowEdit_testcases.java:218)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_publish_status -->
  <testcase name="validate_the_publish_update" time="17.964" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_the_publish_update(WorkflowEdit_testcases.java:231)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_the_publish_update -->
  <testcase name="update_workflow_publish_status_to_previous" time="17.439" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.update_workflow_publish_status_to_previous(WorkflowEdit_testcases.java:242)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_workflow_publish_status_to_previous -->
  <testcase name="validate_the_publish_update_to_previous" time="17.858" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_the_publish_update_to_previous(WorkflowEdit_testcases.java:255)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_the_publish_update_to_previous -->
  <testcase name="inactivate_workflow" time="17.156" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.inactivate_workflow(WorkflowEdit_testcases.java:266)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- inactivate_workflow -->
  <testcase name="validate_that_the_workflow_is_inactive" time="16.885" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_the_workflow_is_inactive(WorkflowEdit_testcases.java:279)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_the_workflow_is_inactive -->
  <testcase name="activate_workflow" time="17.484" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.activate_workflow(WorkflowEdit_testcases.java:290)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- activate_workflow -->
  <testcase name="validate_that_the_workflow_is_active" time="18.094" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.validate_that_the_workflow_is_active(WorkflowEdit_testcases.java:303)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validate_that_the_workflow_is_active -->
  <testcase name="click_cancel_button" time="16.926" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.click_cancel_button(WorkflowEdit_testcases.java:327)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- click_cancel_button -->
  <testcase name="empty_name_field_and_save" time="17.775" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.empty_name_field_and_save(WorkflowEdit_testcases.java:339)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- empty_name_field_and_save -->
  <testcase name="empty_color_field_and_save" time="17.337" classname="settings.WorkflowEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [MMS - Workflow] but found [MMS - Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [MMS - Workflow] but found [MMS - Dashboard]
	at login.DashboardPage.clickWorkflow(DashboardPage.java:332)
	at settings.WorkflowEdit_testcases.empty_color_field_and_save(WorkflowEdit_testcases.java:353)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- empty_color_field_and_save -->
</testsuite> <!-- WORKFLOW TESTCASES -->
