<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="prikab" name="SEGMENT GROUPS EDIT TESTCASES" tests="15" failures="1" timestamp="9 Nov 2016 02:17:33 GMT" time="931.906" errors="0">
  <testcase name="update_segment_groups_brand" time="57.024" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="update_segment_groups_brand_to_previous" time="59.453" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="update_segment_groups_name" time="54.907" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="update_segment_groups_name_to_previous" time="55.479" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="update_segment_groups_type" time="54.404" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="update_segment_groups_type_to_previous" time="54.13" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="update_segment_groups_description" time="51.3" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="inactivate_segment_groups" time="53.829" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="activate_segment_groups" time="53.815" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="update_segment_groups_clientname" time="53.854" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="update_segment_groups_clientname_to_previous" time="63.924" classname="configuration.SegmentGroupsEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at configuration.SegmentGroupsPage.validateUpdates(SegmentGroupsPage.java:158)
	at configuration.SegmentGroupsEdit_testcases.update_segment_groups_clientname_to_previous(SegmentGroupsEdit_testcases.java:153)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_segment_groups_clientname_to_previous -->
  <testcase name="empty_name_field_in_segmentGroups_edit_page" time="52.744" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="select_button_cancel_in_segmentgroups_edit_page" time="44.318" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="archive_segment_groups" time="31.564" classname="configuration.SegmentGroupsEdit_testcases"/>
  <testcase name="restore_segment_groups" time="47.95" classname="configuration.SegmentGroupsEdit_testcases"/>
</testsuite> <!-- SEGMENT GROUPS EDIT TESTCASES -->
