<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="INTEGRATION TEST RBAC"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="35.282">
  <properties />
            <testcase name="integration_create_a_permission_groups_1" time="24.816" classname="integration.rbac_testcases">
                <failure type="java.lang.AssertionError"
                  message="expected [CODA - Permission Groups] but found [CODA - Permissiongroups - Add]"
              >
<![CDATA[java.lang.AssertionError: expected [CODA - Permission Groups] but found [CODA - Permissiongroups - Add]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:190)
  org.testng.Assert.assertEquals(Assert.java:200)
  access.PermissionGroupsAddPage.clickSave(PermissionGroupsAddPage.java:67)
  integration.rbac_testcases.integration_create_a_permission_groups_1(rbac_testcases.java:18)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="validate_user_wit_testrole2" time="8.186" classname="integration.rbac_testcases" />
                <testcase name="delete_role_from_database_2" time="2.280" classname="integration.rbac_testcases" />
      
</testsuite>
